# Generated by Django 4.1.3 on 2023-02-12 21:29

import core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_partners', models.CharField(choices=[('Bauer', 'Bauer'), ('Reebok', 'Reebok'), ('Easton', 'Easton'), ('CCM', 'CCM'), ('FISHER', 'FISHER')], default='CCM', max_length=6)),
                ('location', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Название Бренда',
                'verbose_name_plural': 'Названия Брендов',
                'ordering': ['name_partners'],
            },
        ),
        migrations.CreateModel(
            name='StoresPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.EmailField(max_length=254)),
                ('location', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Магазин партнер',
                'verbose_name_plural': 'Магазины партнеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, validators=[core.validators.check_phonenum])),
                ('location', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['first_name'],
            },
        ),
    ]
