# Generated by Django 4.1.3 on 2023-02-12 21:29

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('contact', models.EmailField(max_length=254)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('sex', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=5)),
                ('role', models.CharField(choices=[('Forward', 'Forward'), ('Defender', 'Defender'), ('GoalKeeper', 'GoalKeeper')], default='Forward', max_length=10)),
                ('year', models.IntegerField()),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3)),
                ('phone_number', models.CharField(max_length=13, validators=[core.validators.check_phonenum])),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.purchaser')),
            ],
            options={
                'verbose_name': 'Данные о покупке',
                'verbose_name_plural': 'Данные о покупках',
                'ordering': ['value'],
            },
        ),
    ]
