# Generated by Django 4.1.3 on 2023-02-12 21:29

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('B_U', 'B_U'), ('New', 'New')], default='New', max_length=3)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('model', models.CharField(choices=[('Stick', 'Stick'), ('Hockey_skates', 'Hockey_skates'), ('Gloves', 'Gloves'), ('Knee_pad', 'Knee_pad'), ('Shoulder_pad', 'Shoulder_pad'), ('Helmet', 'Helmet'), ('Puck', 'Puck'), ('Chest_pad', 'Chest_pad')], default='Stick', max_length=15)),
                ('brand', models.CharField(choices=[('Bauer', 'Bauer'), ('Reebok', 'Reebok'), ('Easton', 'Easton'), ('CCM', 'CCM'), ('FISHER', 'FISHER')], default='CCM', max_length=6)),
                ('price', models.IntegerField(default=100)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('RUB', 'RUB')], default='RUB', max_length=3)),
            ],
            options={
                'verbose_name': 'Экиперовка',
                'verbose_name_plural': 'Экиперовка',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('contact', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['name'],
            },
        ),
    ]
