# Generated by Django 4.1.3 on 2023-02-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('B_U', 'B_U')], default='New', max_length=5),
        ),
    ]
